### ISSUE TITLE
Question: Will you support historical or intraday candlestick data API in future?

### ISSUE THREAD

**Issue by algo2t** [Pritesh-Mhatre/python-library#1]
Question: Will you support historical or intraday candlestick data API in future?
Only zerodha supports these and it is too costly. Do you have any plans to support it in future?
Having everything in single platform helps a lot.

**Comment by Pritesh-Mhatre** [comment]
Thanks for your question.

Unlikely as it needs an entire setup. It is like starting a new business venture & unfortunately we do not have developer resources to do that.
Becoming a market data vendor is not just development intensive task but it also requires considerable investment to purchase data subscription from the exchanges.
