### ISSUE TITLE
Please add support for SAS Online

### ISSUE THREAD

**Issue by algo2t** [Pritesh-Mhatre/python-library#2]
Please add support for SAS Online people might benefit from it.

I have already written a python library for it known as [alphatrade ](https://github.com/algo2t/alphatrade)

I have also added the historical data and intraday data to it. May be you can do so in your code.

Even the websocket is available.

SAS does not support my implementation since alphatrade is based on AliceBlue python module, I think you can take advantage of it.

It is just a suggestion and not actual issue or bug at your end.

And yes your platform is great. Keep up the good work. Just wanted to help people with algo trading so created my own implementation for SAS online. SAS team says their APIs are not yet stable for algo trading but till now I have not faced much problem (though few glitches come which are there even in kiteconnect).

**Comment by Pritesh-Mhatre** [comment]
Thanks for the update. If you see our library it is broker independent. We will add support for SAS on our server side. Our servers do not use python.

We cannot provide live data from our APIs even though it is available due to data license restrictions.
